home:
    pattern: /
    defaults: { _controller: HROSurveyBundle:Default:index}

login:
    pattern: /inloggen
    defaults: { _controller: HROSurveyBundle:Security:login }

login_check:
    pattern: /inloggen_check

logout:
    pattern: /uitloggen

survey_list:
    pattern: /enquetes/
    defaults: { _controller: HROSurveyBundle:Survey:list }

survey_edit:
    pattern: /enquete/edit/{id}
    defaults: { _controller: HROSurveyBundle:Survey:edit }
    requirements:
        id: \d*|nieuw

survey_show:
    pattern: /enquete/{id}
    defaults: { _controller: HROSurveyBundle:Survey:show }
    requirements:
        id: \d*

HROSurveyBundle_daotest:
    pattern:  /dao-test
    defaults: { _controller: HROSurveyBundle:Test:index }